version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: lokal-ai-fe
    ports:
      - '80:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      NEXT_PUBLIC_BACKEND_BASE_POINT: ${NEXT_PUBLIC_BACKEND_BASE_POINT}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}
    restart: unless-stopped
    deploy:
      replicas: 3
    networks:
      - lokal-ai-network

networks:
  lokal-ai-network:
    driver: bridge
